spring.application.name=centro-deportivo-api

spring.datasource.users.jdbc-url=jdbc:mysql://localhost:3306/API_centro_deportivo
spring.datasource.users.username=${USERS_DB_USER}
spring.datasource.users.password=${USERS_DB_PASSWORD}
spring.datasource.users.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.routines.jdbc-url=jdbc:mysql://localhost:3306/routines_db
spring.datasource.routines.username=${ROUTINES_DB_USER}
spring.datasource.routines.password=${ROUTINES_DB_PASSWORD}
spring.datasource.routines.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET_KEY}

# enrollment.expiration.cron=0 0 7 * * *
enrollment.expiration.notification.cron=0 0 7 * * *
enrollment.expiration.notification.days=5

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM}