spring.application.name=centro-deportivo-api

spring.datasource.users.jdbc-url=jdbc:mysql://localhost:3306/API_centro_deportivo
spring.datasource.users.username=${USERS_DB_USER}
spring.datasource.users.password=${USERS_DB_PASSWORD}
spring.datasource.users.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.routines.jdbc-url=jdbc:mysql://localhost:3306/routines_db
spring.datasource.routines.username=${ROUTINES_DB_USER}
spring.datasource.routines.password=${ROUTINES_DB_PASSWORD}
spring.datasource.routines.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET_KEY}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent